
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Statement;
import javax.swing.table.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raj
 */
public class Bill_WardRecord extends javax.swing.JFrame {
Connection con=null;
ResultSet rs=null;

    /**
     * Creates new form Bill_RoomRecord
     */
    public Bill_WardRecord() {
        initComponents();
        con= Connect.ConnectDB();
        Get_Data();
        setLocationRelativeTo(null);
    }
 private void Get_Data(){
         try{
     String sql="select * from bill_ward order by billno";
     DefaultTableModel model = (DefaultTableModel)
jTable1.getModel(); 
     int rows=model.getRowCount();
if (rows>0)
{
for (int i=0; i<rows; i++)
 model.removeRow(0); 
}


Statement stmt = con.createStatement();
             rs= stmt.executeQuery(sql);
 model = (DefaultTableModel) jTable1.getModel();

          while(rs.next())
{
String a = rs.getString("BillNo");
String c = rs.getString("dischargeID");

String n = rs.getString("BedCharges");

String p = rs.getString("BillingDate");
String q = rs.getString("PaymentMode");

String s = rs.getString("TotalCharges");
String t = rs.getString("ChargesPaid");

String v = rs.getString("NoOfDays");

model.addRow (new Object[] {a,c,n,p,q,s,t,v});
}
     
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          
}
    }
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Billing Record");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "BillNo", "Admit ID", "Bed Charges", "Billing Date", "Payement Mode", "Total Charges", "Charges Paid", "No. Of Days"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       try{
            con=Connect.ConnectDB();
            int row= jTable1.getSelectedRow();
            this.hide();
            Bill_Ward frm = new Bill_Ward();
            frm.setVisible(true);
            String add= jTable1.getModel().getValueAt(row, 0).toString();
            frm.txtBillNo.setText(add);
            
             String add2= jTable1.getModel().getValueAt(row, 1).toString();
            frm.txtAdmitID.setText(add2);
             
             
              
              String add13= jTable1.getModel().getValueAt(row,2 ).toString();
            frm.txtBedCharges.setText(add13);
             
              String add15= jTable1.getModel().getValueAt(row, 3).toString();
            frm.txtBillingDate.setText(add15);
              String add16= jTable1.getModel().getValueAt(row, 4).toString();
            frm.cmbPaymentMode.setSelectedItem(add16);
              
             String add18= jTable1.getModel().getValueAt(row, 5).toString();
            frm.txtTotalCharges.setText(add18);
            String add19= jTable1.getModel().getValueAt(row, 6).toString();
            frm.txtTotalPaid.setText(add19);
             
            
             String add21= jTable1.getModel().getValueAt(row, 7).toString();
            frm.txtNoOfDays.setText(add21);
             
            
            frm.btnUpdate.setEnabled(true);
            frm.btnDelete.setEnabled(true);
            frm.Transaction.setEnabled(false);
             
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.hide();
       Bill_Ward frm = new Bill_Ward();
       frm.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill_WardRecord().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
